### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by gogo1704** [MightyPirates/TIS-3D#151]
Minecraft 1.17.1
TIS-3D 1.6.6

First off, it's annoying that when i close the manual , it resets to main page instead returning to the page I was reading before.

![image](https://user-images.githubusercontent.com/33185192/144935991-8e3293a4-2648-4313-ba86-50b999911858.png)
![image](https://user-images.githubusercontent.com/33185192/144936408-13e9b8fc-1ddc-4c81-9585-d528a8095695.png)
![image](https://user-images.githubusercontent.com/33185192/144936557-20c88e3e-18e4-4c47-b610-b7b859a5257c.png)
I can connect 16 casings before computer stops running.

![image](https://user-images.githubusercontent.com/33185192/144938326-49927c42-af6c-4bdf-ad8d-48ad16202fc1.png)
Its's not said what values those character have. (From my testing it appears the bell is 0x07 and rest is next in that order)

![image](https://user-images.githubusercontent.com/33185192/144937538-3af358cf-1cce-4c89-8cb8-a242bea2da71.png)
It would be nice if there was an exact range in number of blocks or something, but it's not important if you go for that TIS manual feel .(Since "...omissions are generally due to the requirements of possible interpretation to satisfy vendor specific needs")

![image](https://user-images.githubusercontent.com/33185192/144938782-959cb15e-8d8f-40a8-acbf-84ff116cdf91.png)
Again ambiguity, but this time I think it's more confusing.

![image](https://user-images.githubusercontent.com/33185192/144939162-be3589d5-688f-44b6-959c-f2f6b794c775.png)
What does this acronym mean? It would be easier to remember for some players if they knew full expansion.

Thx <3 Great mod

**Comment by esotericist** [comment]
the casings mention is an artifact of when the default *was* eight. the default is currently 16, docs don't reflect that. i wonder if it's possible for markdown manual to insert the value from the server config?

> Its's not said what values those character have. (From my testing it appears the bell is 0x07 and rest is next in that order)

i think the intent is you just use the constant rather than the value? i mean, it might change. you never know.

i agree on the infrared/timer doc gaps. i have no idea what the range is, but it sure as hell seems more than 'short' to me, since i watched the particles sail into the distance far out of reach of anything i'd planned to do. i might test that later myself

BWTM: But Wait, There's More. cultural reference/idiom.

note that you're still limited to 40 lines of code for a single program by default.

**Comment by gogo1704** [comment]
> i think the intent is you just use the constant rather than the value? i mean, it might change. you never know.

im not sure i understand. What i mean is that those characters (\b \n etc.) dont exist in codepage 437 and manual doest say what their value is.

> note that you're still limited to 40 lines of code for a single program by default.

how many lines does a single page have?
Cuz iirc i had full 3 page programs
