### ISSUE TITLE
Sodium mod with either 1.19.2/1.19.3 tis-3d causes display module placed on casing to become transparent #1567

### ISSUE THREAD

**Issue by ComputerJock** [MightyPirates/TIS-3D#171]
Placing a display module on a casing causes both to become transparent. This happens for both 1.19.2 and 1.19.3 TIS-3D when the Sodium mod is also enabled.

sodium-fabric-mc1.19.2-0.4.4+build.18.jar
tis3d-MC1.19.2-fabric-1.7.1+b86ec05.jar

The Sodium mod has a million options so perhaps one of them affects this bug.

Reproduction Steps
Run either tis-3d versions for 1.19.2 or 1.19.3 with the sodium mod enabled. Place a display module on a casing block.

Java version
Java 17 as shipped by Mojang

CPU
Intel core i7

GPU
AMD Radeon HD 6900 Series

Additional information
I ran with only tis-3d & enabled/disabled sodium
I also ran with the entire suite of mods I use and enabled/disabled sodium

![With sodium](https://user-images.githubusercontent.com/23107501/211174573-9777a336-6816-4ceb-b02b-f532fa51ce9f.png)
![No sodium](https://user-images.githubusercontent.com/23107501/211174575-0fda6340-6547-46e7-821f-28b355004349.png)

**Comment by Shazuli** [comment]
I might add installing [Indium](https://www.curseforge.com/minecraft/mc-mods/indium), which is required for a lot of mods' special rendering, causes a crash.

**Comment by fnuecke** [comment]
From what I can tell, Sodium completely replaces Minecrafts regular chunk rendering pipeline.  Which also means they disable Fabric's custom model baking hooks (i.e. the `FabricBakedModel` interface).  And they don't re-implement them in their pipeline.  So they call into a custom baked model using the regular `BakedMode.getQuads` method, instead of Fabric's `FabricBakedModel.emitBlockQuads`. Which cannot work (model needs the extra context provided by the Fabric version).

Guess I'll disable custom baked models (and with them the facade module) when Sodium is present.
