### ISSUE TITLE
Add onInstalled and onUninstalled to Module

### ISSUE THREAD

**Issue by Vexatos** [MightyPirates/TIS-3D#25]
Those methods would take the item stack used for installation / the itemstack you get back when uninstalling a module as a parameter. This would allow initializing from the stack's NBT data as well as writing own data back to the ItemStack for persistence.

**Comment by fnuecke** [comment]
For initialization I'd say [`ModuleProvider.createModule`](https://github.com/MightyPirates/TIS-3D/blob/master/src/main/java/li/cil/tis3d/api/module/ModuleProvider.java#L31) is well enough suited (just grab the NBT from the stack provided there). Alternatively `onEnable` (read on).

For saving what you'd probably really want is to write it back to the stack in `onDisable`, so it's also saved on chunk unloads and such? At least that should be called there, too... I think. If it isn't yet I just forgot. So that plus I'll add `IInventory` to the `Casing` interface and that should be all you need, right?

Out of curiosity, what state do you want to store in the module's item stack? (Since they're ususally non-persistent / reset when the computer powers down I didn't really expect having to store data on their items.)

**Comment by Vexatos** [comment]
I do not have any intentions to use it just yet, I just thought it might be nice if you could make the module, in case something changes "physically", keep this state even when you uninstall it and install it inside some other casing.

**Comment by fnuecke** [comment]
06002eaee3846585c4f500cb08d80d43116c5c8a
