### ISSUE TITLE
Crash trying to run on linux mint

### ISSUE THREAD

**Issue by adegarimore** [MightyPirates/TIS-3D#43]
http://pastebin.com/Em0SEgat

Please let me know if there is any more information I can give you to help solve this problem.

**Comment by dgelessus** [comment]
The mod seems to require Java 8, and you're running Java 7. You can download Oracle's Java 8 runtime from https://java.com/en/download/manual.jsp, though if possible you should look for an implementation of Java 8 in your package manager. Though Oracle's JRE/JDK might not be included there (because it's not FOSS) and there might not be an OpenJDK 8 yet.

(Honestly I'm very badly informed about the situation regarding Java on Linux. Point is, you need Java 8.)

**Comment by adegarimore** [comment]
Ahh. I was not aware that java 8 was required. Thanks. I'm not sure if I can get java 8 or not, but either way, that answers my question. :smiley: 

Also, You're username is creepily similar to mine :stuck_out_tongue_closed_eyes:
