### ISSUE TITLE
TIS-3D Translation Chinese

### ISSUE THREAD

**Issue by Cyl18** [MightyPirates/TIS-3D#44]
Hey!Your mod is amazing!
This is TIS-3D-Translation-Chinese.
[TIS-3D Translation Chinese.zip](https://github.com/MightyPirates/TIS-3D/files/170334/TIS-3D.Translation.Chinese.zip)

**Comment by fnuecke** [comment]
Thanks a lot! Would you mind making a pull request?
(If you don't know how to, see Github's [forking](https://help.github.com/articles/fork-a-repo/) and [pull requesting](https://help.github.com/articles/using-pull-requests/) guides. If you can't figure it out no worries, I'll look into adding manually when I have the time!)

**Comment by Cyl18** [comment]
Oh,I'm sorry.
The manual is not working.(I had not tested.)
The Markdown files are correct, but if I open the manual, the game will crash.
I don't know how to fix it.
![untitled](https://cloud.githubusercontent.com/assets/14993992/13724027/c8528ed8-e8b2-11e5-93cf-caec590c54d2.png)

When I repair it,I will make a pull request.

**Comment by 3TUSK** [comment]
@cyl18 ~~Do you have any crash-report(s) or any kinda of log(s)? Otherwise it's just waste of time.~~
Just tested it by myself, the game will _freeze_ without any useful information generated. 
Tested under 1.7.10-Forge10.13.4.1614, with many of other mods installed. If necessary I'll provide the full mods list.
Still have no idea why that happened, and Im trying digging into codes to see if there is something related.

**Comment by 3TUSK** [comment]
Okay here is what I found. 
First, I don't think it is caused by broken translation, because I have double checked the index.md and found no problem.
Second, I set up a new MultiMC instance and installed Forge 10.13.4.1614 and TIS-3D only, switched language to Simplified Chinese and loaded the translation as a resourcepack. This time, I notice that the game seems not to crash - because minecraft is still playing music. 
Last but not least, I use VisualVM and notice this:
![image](https://cloud.githubusercontent.com/assets/9113033/13761854/70e5e1da-ea11-11e5-9678-f5a8a6576069.png)
My Java skill is not good enough and I cannot determine whether it is the origin of game freezing. Hope it will be helpful.

**Comment by 3TUSK** [comment]
@fnuecke Further test shows that the markdown syntax
````
`something`
````
cannot apply in any Chinese translation file due to unknown reason. When I try to open any page that contains `` and zh_CN is current language, game will immediately _freeze_. 
Currently a workaround can be a removal of all `` in all Chinese translation files. However, do you have any idea of its origin?

**Comment by fnuecke** [comment]
Ahh, the font renderer for code segments only has a _very_ [limited set of characters](https://github.com/MightyPirates/TIS-3D/blob/master-MC1.8.9/src/main/resources/assets/tis3d/textures/font/normal.png). Thanks for digging into that.

I'm guessing it somehow gets locked up when encountering an unknown char, I'll look into fixing that.

However, that will just lead to unrenderable characters to be missing/replaced by `?`s, so I'm afraid I'll have to ask you to keep it simple in code segments, sorry.

**Comment by 3TUSK** [comment]
@fnuecke Sorry for bothering again, but after I removed all the code segments in `index.md`, thing still have no change - that said, I suspected that it is something else that freezes game, 'cause I have found that `moduleAudio.md` and `moduleBundedRestone.md` has the same problem. 
I will keep testing on that until I found the problem.

Edit: After a thorough check on all markdown files, I suspect that the problem is on starting a new line. So far I have manually fixed almost of those broken files. I probably can open a pull request soon or later; however, my friends and I have a strong feeling that the tone and writing style need further review.

**Comment by fnuecke** [comment]
Ohh, nevermind, I'm an idiot. I got distracted by the mention of the code segment, but the stack in the screenshot clearly says it's in the text segment. I'll investigate and fix it.

**Comment by fnuecke** [comment]
Allright, fixed the hang!

**Comment by dgelessus** [comment]
@fnuecke "very limited set of characters" `;)`

![normal.png](https://cloud.githubusercontent.com/assets/6641959/14057164/0ed61768-f2f8-11e5-8d3a-6fc48872c7fa.png)

(just kidding. the image took a really long time to load, at least a second or so...)
