### ISSUE TITLE
Bundled redstone module incompatible with EnderIO's insulated redstone conduit

### ISSUE THREAD

**Issue by josephcsible** [MightyPirates/TIS-3D#48]
The bundled redstone module does not appear to be compatible with EnderIO's insulated redstone conduit. I tried this on two different setups, neither of which worked: Minecraft 1.7.10 with EnderIO 2.3.0.427 and TIS-3D 0.9.0.66, and Minecraft 1.10.2 with EnderIO 3.0.1.74 and TIS-3D 0.9.0.1.

**Comment by josephcsible** [comment]
I tried to implement this in TIS-3D myself, and I noticed that EnderIO doesn't really have a proper API in modern versions. I opened SleepyTrousers/EnderIO#3548 about it.

**Comment by fnuecke** [comment]
Started work on this for 1.10 in [a branch](https://github.com/MightyPirates/TIS-3D/tree/enderio-MC1.10), can't get it to compile without adding a ton of other dependencies (in fact, I gave up trying after a few), because the API still isn't quite there yet (still need internal classes to *read* bundled redstone state from what I can tell).

**Comment by Vexatos** [comment]
See https://github.com/MightyPirates/OpenComputers/pull/2134.

**Comment by fnuecke** [comment]
I did. I don't know what magic you did to make OC compile, though.
(inb4 "used Scala")

**Comment by josephcsible** [comment]
Perhaps [RSWires](https://minecraft.curseforge.com/projects/rswires) would be good to integrate with.

**Comment by fnuecke** [comment]
Bundled Redstone is pretty much dead in this mode. No immediate plans to bring it back.
