### ISSUE TITLE
[Idea] Make sidebar of keypad module optionally an "enter" key

### ISSUE THREAD

**Issue by thecodewarrior** [MightyPirates/TIS-3D#61]
My idea was to make the blue bar on the side of the keypad some kind of enter key, which maybe could be enabled/disabled by writing a 1 or a 0 to the keypad or some simple crafting recipe (keypad + button?). Maybe it would output -1 when it is pressed.

**Comment by fnuecke** [comment]
I see two problems with that, 1. it'd not be very intuitive (because it doesn't look like an enter key), 2. it'd be fiddly and probably get annoying quickly (relatively thin area to have to hit).

What would the benefit be? If it's to allow inputting multiple digits of a single number to output, that'd then also need a display, IMHO, which would make things even more cramped :/

**Comment by fnuecke** [comment]
Given there's the terminal module now which can be used for multi-digit input, I'm even less convinced of this, sorry :P I think the keypad is fine as it is after all.
