### ISSUE TITLE
Bundled Redstone Module not functional?

### ISSUE THREAD

**Issue by HyperHamster** [MightyPirates/TIS-3D#69]
Minecraft: 1.10.2
TIS-3D: 1.2.2.20
Project Red - Integration: 4.8.4.49 
Ender IO: 3.1.192

From what I can tell this module doesn't do anything whatsoever. I initially tried interfacing with it using Ender IO's Redstone Conduits to no effect but after reading the related issue #48 it seemed it was simply an incompatability with Ender IO. I then installed Project Red - Integration in attempt to interface with this module again to no effect. Is there a mod that implements bundled redstone functionality that the Bundled Redstone Module is intended for, or does it exist only to be implemented in the future?

**Comment by fnuecke** [comment]
The only implemented bundled redstone API currently is the one in charset wires I believe. I'll look into Project Red integration (and see if the EIO one compiles by now) when I can.

**Comment by HyperHamster** [comment]
[Wires and gates were removed from Charset](http://asie.pl/Projects/Minecraft/Mods/Charset/Rejects) essentially orphaning their API. Because of this [Ender IO is no longer considering adopting it](https://github.com/SleepyTrousers/EnderIO/issues/3548#issuecomment-321227912) as a replacement for its temporary non-API in favor of adopting another mod's API (like Project Red's) or creating their own. I am not aware of another mod with a proper Bundled Redstone API other than Project Red (Edit: for 1.10.x and up).

**Comment by esotericist** [comment]
Right now, the closest thing we have to bundled redstone in minecraft 1.11+ is the [redstone wire connector in Immersive Engineering](https://ftb.gamepedia.com/Redstone_Wire_Connector_(Immersive_Engineering)). 

It has slightly different semantics than the traditional bundled cable implementations, but it does appear that it can serve a similar purpose since it has the expected 16 channels, and transmits a 0 to 15 signal to receivers with a matching channel setting.

The primary semantic difference is that an IE input wire connector (as in input to the network) can only transmit on one channel at a time; swapping channels requires it to drop anything it might be transmitting on a previous channel implicitly before transmitting on the new channel.

**Comment by fnuecke** [comment]
Thanks for the info, I'll look into that when I can.

**Comment by esotericist** [comment]
There is an API, but it seems to be assuming you're implementing your own wire connector rather than directly tinkering with the internal settings of one.

I did do some lightweight testing of editing the nbt of a connector and seeing how it responded, and I do believe it could be done that way, although obviously that would be ugly, brittle, and generally the wrong way to do it. 😀 

Bright side to implementing your own [connectable](https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/java/blusunrize/immersiveengineering/api/energy/wires): you could conceivably be able to more-or-less mimic the semantics of bundled cables from older stuff with regards to how it works for TIS-3d.

I'm not sure you if you want to bother with that, though.

**Comment by josephcsible** [comment]
I considered using the Immersive Engineering API in one of my mods, but I ended up deciding against it because the author never gave it a license, so using it might be considered copyright infringement.

**Comment by esotericist** [comment]
It does look like he's revisiting that: https://github.com/BluSunrize/ImmersiveEngineering/pull/2543
So at the least that specific concern shouldn't be a thing for long.

**Comment by esotericist** [comment]
I'm not seeing an API in the source here, so I don't know how difficult it would be to make use of, but [Automated Redstone](https://minecraft.curseforge.com/projects/automated-redstone/) has some bundled-cable-like things. They support redstone signals outside of the range of 0-15, which... could be good, could be bad, could be another case of Results Are Vendor Specific.

As a personal aside, despite the polish concerns the mod looks like approximately the right pairing for TIS-3d for getting actual work done; getting data into TIS-3d is the hardest part, in my experience. Especially if you're not using another computer mod to do it.

**Comment by esotericist** [comment]
Still alpha so might not be something you want to engage with yet, but [rswires](https://minecraft.curseforge.com/projects/rswires) is a 1.12 work-in-progress that is mimicing the traditional rp2 style wiring.

According to [this](https://minecraft.curseforge.com/projects/simplelogic) there's some plans for API adjustments, so that should probably shake out first.

**Comment by ghost** [comment]
While technically lacking the bundled cabling, perhaps the infra-redstone system might work better due to how it carries values? [Curse page](https://minecraft.curseforge.com/projects/infraredstone). The wiki has some good info.

**Comment by asiekierka** [comment]
SimpleLogic Wires is now supported in 1.12.2.

**Comment by fnuecke** [comment]
In the latest versions there's no real built-in support for bundled redstone anymore. No immediate plans to bring it back.
