### ISSUE TITLE
[SUGGESTION] Facades

### ISSUE THREAD

**Issue by Shazuli** [MightyPirates/TIS-3D#92]
***Hi***

I think TIS-3D would be great with a pseudo-module that when crafted needs a block and when installed and activated displays the texture of the block it was crafted with.

Example situation:
![2019-04-18_21 37 22](https://user-images.githubusercontent.com/9884180/56386508-40f94980-6222-11e9-8017-50fd3cc86dd7.png)

**Comment by Shazuli** [comment]
An example where that would be great and kind of hard to solve unless you can live with pieces sticking out:
![door](https://user-images.githubusercontent.com/9884180/56425919-7e0f1b80-62b6-11e9-863a-a348638fa2b0.gif)

**Comment by fnuecke** [comment]
Done. Pushed for 1.10 through 1.12 to Curse, awaiting approval. Will probably be looking at how to do this in Fabric at a later point.

Works a bit differently than you proposed: after installing can be configured by using a block on it or placing one in front of the module, and the casing will always look like that block on the module's side.

Heuristic for allowed blocks is pretty strict for now. If it turns out a bunch of blocks can be used/cannot be used that should not be usable/should be usable I might add a black and whitelist later.
